version: "3.9"

services:

  flask_db:
    container_name: "database"
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: contactsdb
    ports:
      - "3306:3306"
    networks:
      - backend

  flask_app:
    container_name: "web"
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    depends_on:
      - flask_db
    links:
      - flask_db
    networks:
      - backend
    
  
      
networks:
  backend:
    driver: bridge
    name: backend
